[Telegram]
api_id = 22422808
api_hash = f7c50d7d086fe9f0c8cf3fc21c59d570
admin_id = 502495882
channel_id = @ismeweiss

[Settings]
channels = @unknownselt, @lovi_tovar1, @za5zvezd, @vykup_keshbek6, @cashzaotzivozon, @pushwboz, @WBrublic, @zayachya_lapkaa, @tovarsozona, @cashback_za_otzivv, @shtrihkodhalyavy, @WBrubliRu, @wbrublipro, @WBrubliCashN, @salenawb, @Skid_best, @tovarzacash, @walrus_best_cashback, @keshbek7, @skidkology, @cashbackzaotziv, @WILDBERRIES_DARIT_HALYAVA, @globalotzivi, @grcashback, @wildberrieskesh, @CashikWB, @reclamawbozonya, @madiko431, @pokupkiozonwb, @tovarotzuvi, @supertovariwb, @wb_shara, @samovykup, @tovarzaotzivdarom, @vikuptovarawb, @cashback_otzivi, @HalyavaWildberriess, @premiumwbozon, @MIzaZOG, @tvoya_skidki, https://t.me/+85iq7OEoZEJiMjgy, https://t.me/+bdg7N4KI9lNmMmIy, @darimzaotzyv, @HAXODKI_PAZDACHI, @cashback_wb_and_ozonn, @keshbek_za_otzyv2, @wb_ozon_tovary, @discounts_cashback5, @feedback_cashback, @cashbacknutie, @tovarzakesh, @keshbek_za_otziv, @cashback_Wb_Ozon, @salenawb, @SALEHOTWB, @tovarzaotzyvvy, @vikup_razdacha_kashback, @tvoy_vigoda, @cashbackLiza, @cashbackwbozonfree, @CASH_Trash1000, @tovar_za_otzyv_vykup_cashback, @labbijetest, @tovarwbo, @WBshoppers, @for_free_wb, @besplatno_skidki_wb_ozon, @Cashback_puk, @kesh_vykup, @wb_ozon_reviews, @super_cash_back, @anju2884, @backcashwb, @styleweare, @magikeda, @sawey_channel, @nahodki_WB_sales
keywords = 100%, 100 %, бесплатно,  0 руб,  0 рублей
dedup_window_hours = 24




# Прокси 3: h3.kotov.store
mtproto_proxy = 94.183.221.198:443:ee82eab1d3f1b8b7ee93e757a79ed467db676f6f676c652e636f6d
