[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:main]
command=python3 main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/main.log
stderr_logfile=/var/log/supervisor/main_err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=PYTHONUNBUFFERED="1"

[program:edit_config_bot]
command=python3 edit_config_bot.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED="1"